cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - node_modules

test_async_node_latest:
  image: node:latest
  script:
    - npm install
    - npm run depcruise
    - npm run lint
    - npm run test
  except:
    - tags

test_async_node_14:
  image: node:14
  script:
    - npm install
    - npm run test
  except:
    - tags
    - web

pages:
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - tags
    - web
