cache:
  key: "$CI_JOB_NAME"
  untracked: true
  paths:
    - node_modules

test_async_node:
  image: node:latest
  script:
    - npm install
    - node --run=depcruise
    - node --run=lint
    - node --run=test:cover
  except:
    - tags

pages:
  image: node:latest
  script:
    - npm install
    - node --run=build
  artifacts:
    paths:
      - public
  only:
    - tags
    - web
