import { readFileSync } from "node:fs";
import prettier from "prettier";

const $package = JSON.parse(
  // eslint-disable-next-line security/detect-non-literal-fs-filename
  readFileSync(new URL("../package.json", import.meta.url), "utf8")
);

process.stdout.write(
  prettier.format(
    `// generated by tools/get-version.mts - edits will be overwritten\nexport const version = "${$package.version}";\n`,
    {
      parser: "babel",
    }
  )
);
