import { readFileSync } from "node:fs";
import { format } from "prettier";

const $package = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8"),
);
const lVersionSource = await format(
  `// generated by tools/get-version.mts - edits will be overwritten\nexport const version = "${$package.version}";\n`,
  {
    parser: "babel",
  },
);
process.stdout.write(lVersionSource);
